export enum QueryTypes {
  "BIO_INFO" = "BIO_INFO",
  "EXPERIENCES" = "EXPERIENCES",
  "PAGE_VIEWS" = "PAGE_VIEWS",
  "TOTAL_VIEWS" = "TOTAL_VIEWS",
  "STATISTICS" = "STATISTICS",
  "SESSIONS" = "SESSIONS",
}