name: Deploy Store App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git for SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          HOST: 157.173.205.31
          USERNAME: root
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
            set -e
            echo "Logging into VPS at $HOST"
            cd /var/www/store-web
            echo "Pulling latest code"
            export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa"
            git pull origin main
            git fetch origin
            git reset --hard origin/main
            docker build -t store-web:latest .
            docker run -d --name store-web --network app_network -p 3000:3000 \
              -e NEXT_PUBLIC_NODE_ENV=production \
              -e NEXT_PUBLIC_SERVER_URL=https://api.themirzaliyev.store \
              store-web:latest
            echo "Deployment complete!"
          EOF
