name: Deploy Store App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.STORE_WEB_KEY }}

      - name: Deploy to VPS
        env:
          HOST: 157.173.205.31
          USERNAME: root
        run: |
          # SSH into VPS and perform the deployment
          ssh -A -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
            set -e
            echo "Logged into VPS at $HOST"

            cd /var/www/store-web
            ssh -T git@github.com || echo "Failed to connect to GitHub via SSH"
            echo "Pulling latest code from GitHub"
            git pull origin main
          EOF
